name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
# TODO: Temporarily disabling
on:
  push:
    tags:
      - '*'

jobs:
  cypress:
    runs-on: ubuntu-latest

    container: ubuntu:latest


    services:
      foundry:
        image: felddy/foundryvtt
        ports:
          - 30000:30000
        env:
          FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
          FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}

    steps:
      - name: Install dependencies
        run: apt-get -y update; apt-get -y install curl

      #- name: Create Test file
      #  run: echo "Test" > /tmp/test-file

      #- name: Cache Test file
      #  uses: actions/cache@v3
      #  with:
      #    key: test-file
      #    path: /tmp/test-file

      - name: Verify service is up
        run: curl http://foundry:30000/; sleep 120; curl http://foundry:30000/