name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    # TEMP: Simple curl container to verify plumbing
    container: ubuntu:latest


    services:
      # TEMP: Starting with a hello world container to explore plumbing
      foundry:
        image: felddy/foundryvtt
        ports:
          - 3000:3000
        env:
          FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
          FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}

    steps:
      - name: Install dependencies
        run: apt-get -y update; apt-get -y install curl

      #- name: Create Test file
      #  run: echo "Test" > /tmp/test-file

      #- name: Cache Test file
      #  uses: actions/cache@v3
      #  with:
      #    key: test-file
      #    path: /tmp/test-file

      - name: Verify service is up
        run: sleep 120; curl http://foundry:3000/