name: FoundryVTT Integration test 2

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
# TODO: Temporarily disabling
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get -y update; sudo apt-get -y install curl

      - name: Test docker
        run: sudo docker ps
