name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
# TODO: Temporarily disabling
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore FoundryVTT CONTAINER_CACHE
        uses: actions/cache@v3
        with:
          key: container_cache
          path: data/container_cache

      - name: Initialized data directory
        run: mkdir -p data

      - name: Pull FoundryVTT Container
        run: sudo docker pull felddy/foundryvtt:release


      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Launch FoundryVTT and run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          start: >-
            sudo docker run
            --name foundryvtt
            --env FOUNDRY_ADMIN_KEY=test-admin-key
            --env FOUNDRY_USERNAME=${{ secrets.FOUNDRY_USERNAME }}
            --env FOUNDRY_PASSWORD=${{ secrets.FOUNDRY_PASSWORD }}
            --env FOUNDRY_LICENSE_KEY=${{ secrets.FOUNDRY_LICENSE_KEY }}
            --publish 30000:30000/tcp
            --volume ${{ github.workspace }}/data:/data
            felddy/foundryvtt:release
          wait-on: 'http://localhost:30000'
          wait-on-timeout: 120

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'true' }}
        name: Launch FoundryVTT and run Cypress Tests (container cached)
        uses: cypress-io/github-action@v5
        with:
          start: >-
            sudo docker run
            --name foundryvtt
            --env FOUNDRY_ADMIN_KEY=test-admin-key
            --env FOUNDRY_LICENSE_KEY=${{ secrets.FOUNDRY_LICENSE_KEY }}
            --publish 30000:30000/tcp
            --volume ${{ github.workspace }}/data:/data
            felddy/foundryvtt:release
          wait-on: 'http://localhost:30000'
          wait-on-timeout: 120

      - name: List contents of data dir for troubleshooting
        run: find data

      - name: Publish test videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-videos
          path: cypress/videos/
