name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
# TODO: Temporarily disabling
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore FoundryVTT CONTAINER_CACHE
        uses: actions/cache@v3
        with:
          key: container_cache
          path: data/container_cache

      - name: Initialized data directory
        run: mkdir data

      - name: Pull FoundryVTT Container
        run: sudo docker pull felddy/foundryvtt:release

      - name: Launch FoundryVTT
        run: |
          sudo docker run -d \
            --name foundryvtt \
            --env "FOUNDRY_USERNAME=${{ secrets.FOUNDRY_USERNAME }}" \
            --env "FOUNDRY_PASSWORD=${{ secrets.FOUNDRY_PASSWORD }}" \
            --publish 30000:30000/tcp \
            --volume data:/data \
            felddy/foundryvtt:release

      #- name: Launch FoundryVTT
      #  uses: cypress-io/github-action@v5
      #  with:
      #    wait-on: 'http://localhost:30000'
      #    wait-on-timeout: 120

      - name: Curl service
        run: docker attach foundryvtt; sleep 120; curl -v http://localhost:30000/