name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
# TODO: Temporarily disabling
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get -y update; sudo apt-get -y install curl

      - uses: actions/checkout@v3

      - name: Restore FoundryVTT CONTAINER_CACHE
        uses: actions/cache@v3
        with:
          key: container_cache
          path: data/container_cache

      - name: Initialized data directory
        run: mkdir data

      - name: Pull FoundryVTT Container
        run: sudo docker pull felddy/foundryvtt:release

      - name: Launch FoundryVTT
        run: |
          sudo docker run -d \
            --env "FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}" \
            --env "FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}" \
            --publish 30000:30000/tcp \
            --volume data:/data \
            felddy/foundryvtt:release

      - name: Wait for FoundryVTT to Start
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:30000'
          responseCode: '200,302'
          # It shouldn't take more than two minutes to start
          timeout: 120000

      - name: Curl service
        run: curl http://localhost:30000/