name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    # TEMP: Simple curl container to verify plumbing
    container: curlimages/curl


    services:
      # TEMP: Starting with a hello world container to explore plumbing
      helloworld:
        image: strm/helloworld-http
        ports:
          - 80:3000

    steps:
      - name: Verify service is up
        run: curl http://helloworld/; sleep 15; curl http://helloworld/