name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
# TODO: Temporarily disabling
#on: push
on:
  pull_request:
    branches:
      - 'main'
      - 'bheiskell/issue131'
  pull_request_target:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'main'
      - 'bheiskell/issue131'

permissions:
  contents: read

jobs:
  foundryvtt-cypress-test:
    if: github.event.pull_request.head.repo.full_name == 'bheiskell/StarWarsFFG-Enhancements'

    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit

  foundryvtt-cypress-test-fork:
    if: github.event.pull_request.head.repo.full_name != 'bheiskell/StarWarsFFG-Enhancements'

    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      environment: Test