name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
# TODO: Temporarily disabling
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: apt-get -y update; apt-get -y install curl

      - uses: actions/checkout@v3

      - name: Restore FoundryVTT CONTAINER_CACHE
        uses: actions/cache@v3
        with:
          key: container_cache
          path: data/container_cache

      - name: Initialized data directory
        run: mkdir data

      - name: Launch FoundryVTT
        run: >
          sudo docker run -d
            --env FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
            --env FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
            --publish 30000:30000/tcp
            --volume data:/data
            felddy/foundryvtt:release

      - name: Verify service is up
        run: curl http://foundry:30000/; sleep 120; curl http://foundry:30000/