name: FoundryVTT Integration test

# TODO: We would like this step to run on pull requests, but only after some
# approval has been granted to protect the secrets.
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    # TEMP: Simple curl container to verify plumbing
    container: curlimages/curl


    services:
      # TEMP: Starting with a hello world container to explore plumbing
      foundry:
        image: felddy/foundryvtt
        ports:
          - 3000:3000
        env:
          FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
          FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}

    steps:
      - name: Verify service is up
        run: curl http://foundry:3000/; sleep 15; curl http://foundry:3000/